In [3]:
# numpy 사용하기
import numpy as np

In [1]:
data1 =[1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [2]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [5]:
# numpy를 이용하여 array 정의하기
#1. 위에서 만든 python list를 이용
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [7]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [9]:
#2. 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [11]:
arr2.shape

(5,)

In [12]:
# array의 자료형을 확인할 수 있다.
arr2.dtype

dtype('int64')

In [14]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [15]:
arr3.shape

(5,)

In [17]:
arr3.dtype

dtype('float64')

In [18]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
arr4.shape

(4, 3)

In [22]:
arr4.dtype

dtype('int64')

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
# np.zeros()함수는 인자로 받는 크기만큼, 모든요소가 0인 array를 만든다.

In [27]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones((2,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [29]:
# np.ones()함수는 인자로 받는 크기만큼, 모든요소가 1인 array를 만든다.

In [31]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

TypeError: 'tuple' object is not callable